---
sidebar: sidebar 
permalink: concept-flash-cache.html 
keywords: cloud volumes ontap, flash cache, read-intensive, read, random, databases, email, file services, compression, performance, nvme 
summary: Algumas configurações do Cloud Volumes ONTAP incluem armazenamento NVMe local, que o Cloud Volumes ONTAP usa como Flash Cache para melhor desempenho. 
---
= Cache Flash
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Algumas configurações do Cloud Volumes ONTAP incluem armazenamento NVMe local, que o Cloud Volumes ONTAP usa como _Flash Cache_ para melhor desempenho.



== O que é Flash Cache?

O Flash Cache acelera o acesso aos dados por meio do cache inteligente em tempo real de dados de usuários lidos recentemente e metadados do NetApp . É eficaz para cargas de trabalho aleatórias com uso intensivo de leitura, incluindo bancos de dados, e-mail e serviços de arquivo.



== Configurações suportadas

O Flash Cache é compatível com configurações específicas do Cloud Volumes ONTAP .  Veja as configurações suportadas no https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Notas de versão do Cloud Volumes ONTAP"^]



== Limitações

ifdef::aws[]

* Ao configurar o Flash Cache para o Cloud Volumes ONTAP 9.12.0 ou anterior na AWS, a compactação deve ser desabilitada em todos os volumes para aproveitar as melhorias de desempenho do Flash Cache.  Ao implantar ou atualizar para o Cloud Volumes ONTAP 9.12.1 ou posterior, não é necessário desabilitar a compactação.
+
Pule a seleção das configurações de eficiência de armazenamento ao criar um volume no NetApp Console ou crie um volume e, em seguida, http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["desabilitar a compactação de dados usando a CLI"^] .



endif::aws[]

* O reaquecimento do cache após uma reinicialização não é suportado com o Cloud Volumes ONTAP.


.Tópicos relacionados
* https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Configurações com suporte para Cloud Volumes ONTAP na AWS"^]
* https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurações com suporte para Cloud Volumes ONTAP no Azure"^]
* https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configurações suportadas para Cloud Volumes ONTAP no Google Cloud"^]

