---
settings:
  name: Cloud Volumes ONTAP
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Provedor de nuvem
    default: Todos os provedores de nuvem
    options:
    - name: Serviços Web da Amazon
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azul
      id: azure
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentação do Cloud Volumes ONTAP
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
    - title: Limitações conhecidas
      url: "/reference-limitations.html"
    - title: Notas de versão do Cloud Volumes ONTAP
      url: "/whats-new-ontap.html"
  - title: Começar
    entries:
    - title: Saiba mais sobre o Cloud Volumes ONTAP
      url: "/concept-overview-cvo.html"
    - title: Versões ONTAP suportadas para novas implantações
      url: "/reference-versions.html"
    - title: Comece na Amazon Web Services
      flavor: aws
      entries:
      - title: Início rápido
        url: "/task-getting-started-aws.html"
      - title: Planeje sua configuração
        url: "/task-planning-your-config.html"
      - title: Configure sua rede
        entries:
        - title: Configurar rede AWS
          url: "/reference-networking-aws.html"
        - title: Configurar um gateway de trânsito da AWS
          url: "/task-setting-up-transit-gateway.html"
        - title: Implantar um par de HA em uma sub-rede compartilhada
          url: "/task-deploy-aws-shared-vpc.html"
        - title: Configurar o Cloud Volumes ONTAP para criação de grupo de posicionamento
            da AWS
          url: "/task-configure-placement-group-failure-aws.html"
        - title: Regras de grupo de segurança para AWS
          url: "/reference-security-groups.html"
      - title: Configurar o AWS KMS
        url: "/task-setting-up-kms.html"
      - title: Configurar funções do IAM
        url: "/task-set-up-iam-roles.html"
      - title: Configurar licenciamento
        url: "/task-set-up-licensing-aws.html"
      - title: Use o método de implantação rápida para o Cloud Volumes ONTAP na AWS
        url: "/task-quick-deploy-aws.html"
      - title: Use o método de implantação avançado para o Cloud Volumes ONTAP na
          AWS
        url: "/task-deploying-otc-aws.html"
      - title: Implantar o Cloud Volumes ONTAP em regiões secretas da AWS
        url: "/task-getting-started-aws-c2s.html"
    - title: Comece no Microsoft Azure
      flavor: azure
      entries:
      - title: Saiba mais sobre as opções de implantação do Cloud Volumes ONTAP no
          Azure
        url: "/concept-azure-mktplace-direct.html"
      - title: Introdução ao NetApp Console
        entries:
        - title: Início rápido
          url: "/task-getting-started-azure.html"
        - title: Planeje sua configuração
          url: "/task-planning-your-config-azure.html"
        - title: Configure sua rede
          url: "/reference-networking-azure.html"
        - title: Configure a criptografia usando sua chave
          url: "/task-set-up-azure-encryption.html"
        - title: Configurar licenciamento
          url: "/task-set-up-licensing-azure.html"
        - title: Habilitar modo de alta disponibilidade
          url: "/task-azure-high-availability-mode.html"
        - title: Habilitar VMOrchestratorZonalMultiFD para zonas de disponibilidade
            únicas
          url: "/task-saz-feature.html"
        - title: Inicie o Cloud Volumes ONTAP no Azure
          url: "/task-deploying-otc-azure.html"
        - title: Verificar imagem da plataforma Azure
          entries:
          - title: Visão geral
            url: "/concept-azure-image-verification.html"
          - title: Baixe o arquivo de imagem do Azure
            url: "/task-azure-download-digest-file.html"
          - title: Exportar o arquivo de imagem do Azure
            url: "/task-azure-image-export.html"
          - title: Verificar assinatura do arquivo
            entries:
            - title: Saiba mais sobre a verificação de assinatura de arquivo
              url: "/concept-azure-file-sig-verify.html"
            - title: Verificar assinatura de arquivo no Linux
              url: "/task-file-verification-linux.html"
            - title: Verificar assinatura de arquivo no macOS
              url: "/task-file-verification-mac.html"
      - title: Comece no mercado
        url: "/task-deploy-cvo-azure-mktplc.html"
    - title: Comece a usar o Google Cloud
      flavor: gcp
      entries:
      - title: Início rápido
        url: "/task-getting-started-gcp.html"
      - title: Planeje sua configuração
        url: "/task-planning-your-config-gcp.html"
      - title: Configure sua rede
        url: "/reference-networking-gcp.html"
      - title: Planejar os controles de serviço da VPC
        url: "/reference-vpc-service-controls-gcp.html"
      - title: Criar uma conta de serviço
        url: "/task-creating-gcp-service-account.html"
      - title: Use chaves de criptografia gerenciadas pelo cliente
        url: "/task-setting-up-gcp-encryption.html"
      - title: Configurar licenciamento
        url: "/task-set-up-licensing-google.html"
      - title: Inicie o Cloud Volumes ONTAP no Google Cloud
        url: "/task-deploying-gcp.html"
      - title: Verificação de imagem da plataforma Google Cloud
        entries:
        - title: Visão geral
          url: "/concept-gcp-image-verification.html"
        - title: Converter imagem para o formato Raw no GCP
          url: "/task-gcp-convert-image-raw.html"
        - title: Verificação de assinatura de imagem
          entries:
          - title: Verificar imagens assinadas pelo GCP
            url: "/concept-gcp-verify-signed-image.html"
          - title: Verifique o conteúdo usando OpenSSL
            url: "/task-verify-openssl-gcp.html"
  - title: Use o Cloud Volumes ONTAP
    entries:
    - title: Gerenciamento de licenças
      entries:
      - title: Gerenciar licenças baseadas em capacidade
        url: "/task-manage-capacity-licenses.html"
      - title: Gerenciar assinaturas do Keystone
        url: "/task-manage-keystone.html"
      - title: Gerenciar licenças baseadas em nós
        url: "/task-manage-node-licenses.html"
    - title: Administração de volume e LUN
      entries:
      - title: Criar volumes
        url: "/task-create-volumes.html"
      - title: Gerenciar volumes existentes
        url: "/task-manage-volumes.html"
      - title: Camada de dados inativos para armazenamento de objetos
        url: "/task-tiering.html"
      - title: Conecte um LUN a um host
        url: "/task-connect-lun.html"
      - title: Acelere o acesso aos dados com o FlexCache
        url: "/task-accelerate-data-access.html"
    - title: Administração agregada
      entries:
      - title: Criar agregados
        url: "/task-create-aggregates.html"
      - title: Gerenciar agregados existentes
        url: "/task-manage-aggregates.html"
      - title: Gerenciar configurações de capacidade
        url: "/task-manage-capacity-settings.html"
    - title: Administração de VM de armazenamento
      entries:
      - title: Trabalhar com VMs de armazenamento
        url: "/task-managing-svms.html"
      - title: Gerenciar VMs de armazenamento na AWS
        flavor: aws
        url: "/task-managing-svms-aws.html"
      - title: Gerenciar VMs de armazenamento no Azure
        flavor: azure
        url: "/task-managing-svms-azure.html"
      - title: Gerenciar VMs de armazenamento no Google Cloud
        flavor: gcp
        url: "/task-managing-svms-gcp.html"
      - title: Configurar recuperação de desastres do SVM
        url: "/task-manage-svm-dr.html"
    - title: Segurança e criptografia de dados
      entries:
      - title: Criptografar volumes com criptografia NetApp
        url: "/task-encrypting-volumes.html"
      - title: Gerencie chaves com o AWS Key Management Service
        flavor: aws
        url: "/task-aws-key-management.html"
      - title: Gerenciar chaves com o Azure Key Vault
        flavor: azure
        url: "/task-azure-key-vault.html"
      - title: Gerenciar chaves com o Google Cloud KMS
        flavor: gcp
        url: "/task-google-key-manager.html"
      - title: Melhore a proteção contra ransomware
        url: "/task-protecting-ransomware.html"
      - title: Crie cópias de Snapshot invioláveis para armazenamento WORM
        url: "/reference-worm-snaplock.html"
    - title: Administração do sistema
      entries:
      - title: Atualizar Cloud Volumes ONTAP
        url: "/task-updating-ontap-cloud.html"
      - title: Registre sistemas de pagamento conforme o uso
        url: "/task-registering.html"
      - title: Converter licenças baseadas em nós
        url: "/task-convert-node-capacity.html"
      - title: Parar e iniciar um sistema
        url: "/task-managing-state.html"
      - title: Sincronizar a hora do sistema
        url: "/task-sync-time.html"
      - title: Modificar a velocidade de gravação do sistema
        url: "/task-modify-write-speed.html"
      - title: Alterar a senha do sistema
        url: "/task-change-password.html"
      - title: Adicionar, remover ou excluir sistemas
        entries:
        - title: Adicionar um sistema existente
          url: "/task-adding-systems.html"
        - title: Remover um sistema
          url: "/task-removing.html"
        - title: Excluir um sistema
          url: "/task-deleting-system.html"
      - title: Administração AWS
        flavor: aws
        entries:
        - title: Trabalhar com instâncias EC2 na AWS
          url: "/task-change-ec2-instance.html"
        - title: Alterar tabelas de rotas para pares HA
          url: "/task-change-route-tables.html"
        - title: Configurar a criação do grupo de posicionamento
          url: task-configure-placement-group-failure-aws.html
      - title: Administração do Azure
        flavor: azure
        entries:
        - title: Alterar o tipo de VM do Azure
          url: "/task-change-azure-vm.html"
        - title: Substituir bloqueios CIFS
          url: "/task-overriding-cifs-locks.html"
        - title: Use um Link Privado do Azure ou pontos de extremidade de serviço
          url: "/task-enabling-private-link.html"
        - title: Mover grupos de recursos
          url: "/task-moving-resource-groups-azure.html"
        - title: Segregar o tráfego do SnapMirror no Azure
          url: "/task-segregate-snapmirror-azure.html"
      - title: Administração do Google Cloud
        flavor: gcp
        entries:
        - title: Alterar o tipo de máquina
          url: "/task-change-gcp-machine.html"
      - title: Administração do Gerenciador de Sistemas
        url: "/task-administer-advanced-view.html"
      - title: Administração do CLI
        url: "/task-connecting-to-otc.html"
    - title: Saúde e eventos do sistema
      entries:
      - title: Verificar configuração do AutoSupport
        url: "/task-verify-autosupport.html"
      - title: Configurar EMS
        url: "/task-configure-ems.html"
  - title: Conceitos
    entries:
    - title: Licenciamento
      entries:
      - title: Licenciamento em Cloud Volumes ONTAP
        url: "/concept-licensing.html"
      - title: Saiba mais sobre licenças baseadas em capacidade
        url: "/concept-licensing-charging.html"
    - title: Armazenar
      entries:
      - title: Protocolos do cliente
        url: "/concept-client-protocols.html"
      - title: Discos e agregados
        url: "/concept-storage.html"
      - title: Volumes elásticos na AWS
        flavor: aws
        url: "/concept-aws-elastic-volumes.html"
      - title: Camadas de dados
        url: "/concept-data-tiering.html"
      - title: Gerenciamento de armazenamento
        url: "/concept-storage-management.html"
      - title: Velocidade de gravação
        url: "/concept-write-speed.html"
      - title: Cache Flash
        url: "/concept-flash-cache.html"
      - title: Armazenamento WORM
        url: "/concept-worm.html"
    - title: Pares de alta disponibilidade
      entries:
      - title: Pares de HA na AWS
        flavor: aws
        url: "/concept-ha.html"
      - title: Pares de HA no Azure
        flavor: azure
        url: "/concept-ha-azure.html"
      - title: Pares HA no GCP
        flavor: gcp
        url: "/concept-ha-google-cloud.html"
      - title: Ações durante a aquisição do armazenamento
        url: "/concept-degraded-ha-pair.html"
    - title: Segurança
      url: "/concept-security.html"
    - title: Desempenho
      url: "/concept-performance.html"
    - title: Gerenciamento de BYOL baseado em nó
      url: "/concept-license-management.html"
    - title: AutoSupport e Digital Advisor
      url: "/concept-active-iq.html"
    - title: Configurações padrão
      url: "/reference-default-configs.html"
  - title: Conhecimento e suporte
    entries:
    - title: Registre-se para obter suporte
      url: "/task-support-registration.html"
    - title: Obter ajuda
      url: "/task-get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
