---
sidebar: sidebar 
permalink: reference-versions.html 
keywords: versions, supported versions, new versions, cloud volumes ontap version 
summary: O NetApp Console permite que você escolha entre várias versões diferentes do ONTAP ao criar um novo sistema Cloud Volumes ONTAP . 
---
= Versões ONTAP suportadas para implantações do Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Console permite que você escolha entre várias versões diferentes do ONTAP ao adicionar um sistema Cloud Volumes ONTAP .

Versões do Cloud Volumes ONTAP diferentes das listadas aqui não estão disponíveis para novas implantações. A versão de patch ou a versão genérica (Disponibilidade Geral) em uma versão aqui representa a versão base disponível para implantação. Para obter detalhes sobre os patches disponíveis, consulte a  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-new.html["notas de lançamento versioned"^] para cada versão.

Para obter informações sobre upgrade, consulte link:task-updating-ontap-cloud.html#supported-upgrade-paths["Caminhos de atualização suportados"].

ifdef::aws[]



== AWS

Nó único::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9,7 P5
* 9,5 P6


--
Par HA::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9,7 P5
* 9,5 P6


--


endif::aws[]

ifdef::azure[]



== Azul

Nó único::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--
Par HA::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--


endif::azure[]

ifdef::gcp[]



== Google Cloud

Nó único::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9,7 P5


--
Par HA::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8


--


endif::gcp[]
