---
sidebar: sidebar 
permalink: task-setting-up-gcp-encryption.html 
keywords: encryption, gcp, encryption key, permissions, customer-managed, gcpencryption 
summary: Embora o Google Cloud Storage sempre criptografe seus dados antes de gravá-los no disco, você pode usar as APIs do Console para criar um sistema Cloud Volumes ONTAP que usa chaves de criptografia gerenciadas pelo cliente.  Essas são chaves que você gera e gerencia no GCP usando o Cloud Key Management Service. 
---
= Usando chaves de criptografia gerenciadas pelo cliente com o Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Embora o Google Cloud Storage sempre criptografe seus dados antes de gravá-los no disco, você pode usar as APIs para criar um sistema Cloud Volumes ONTAP que usa _chaves de criptografia gerenciadas pelo cliente_.  Essas são chaves que você gera e gerencia no GCP usando o Cloud Key Management Service.

.Passos
. Certifique-se de que a conta de serviço do agente do Console tenha as permissões corretas no nível do projeto, no projeto onde a chave está armazenada.
+
As permissões são fornecidas no https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["as permissões da conta de serviço por padrão"^] , mas pode não ser aplicável se você usar um projeto alternativo para o Cloud Key Management Service.

+
As permissões são as seguintes:

+
[source, yaml]
----
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
----
. Certifique-se de que a conta de serviço para o https://cloud.google.com/iam/docs/service-agents["Agente de serviço do Google Compute Engine"^] tem permissões do Cloud KMS Encrypter/Decrypter na chave.
+
O nome da conta de serviço usa o seguinte formato: "service-[service_project_number]@compute-system.iam.gserviceaccount.com".

+
https://cloud.google.com/kms/docs/iam#granting_roles_on_a_resource["Documentação do Google Cloud: Usando o IAM com o Cloud KMS - Concedendo funções em um recurso"]

. Obtenha o "id" da chave invocando o comando get para `/gcp/vsa/metadata/gcp-encryption-keys` Chamada de API ou escolhendo "Copiar nome do recurso" na chave no console do GCP.
. Se estiver usando chaves de criptografia gerenciadas pelo cliente e hierarquizando dados para armazenamento de objetos, o NetApp Console tentará utilizar as mesmas chaves usadas para criptografar os discos persistentes.  Mas primeiro você precisa habilitar os buckets do Google Cloud Storage para usar as chaves:
+
.. Encontre o agente de serviço do Google Cloud Storage seguindo o https://cloud.google.com/storage/docs/getting-service-agent["Documentação do Google Cloud: Obtendo o agente de serviço do Cloud Storage"^] .
.. Navegue até a chave de criptografia e atribua ao agente de serviço do Google Cloud Storage permissões de Criptografador/Descriptografador do Cloud KMS.


+
Para mais informações, consulte https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys["Documentação do Google Cloud: Usando chaves de criptografia gerenciadas pelo cliente"^]

. Use o parâmetro "GcpEncryption" com sua solicitação de API ao criar um sistema.
+
*Exemplo*

+
[source, json]
----
"gcpEncryptionParameters": {
    "key": "projects/project-1/locations/us-east4/keyRings/keyring-1/cryptoKeys/generatedkey1"
  }
----


Consulte o https://docs.netapp.com/us-en/bluexp-automation/index.html["Documentação de automação do NetApp Console"^] para mais detalhes sobre o uso do parâmetro "GcpEncryption".
