---
sidebar: sidebar 
permalink: task-sync-time.html 
keywords: set up, setting up, ntp, time, synch 
summary: Especificar um servidor NTP sincroniza o horário entre os sistemas na sua rede, o que pode ajudar a evitar problemas devido a diferenças de horário. 
---
= Sincronize a hora do sistema Cloud Volumes ONTAP usando servidores NTP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configurar servidores Network Time Protocol (NTP) para seus clusters Cloud Volumes ONTAP garante a sincronização precisa do horário do seu cluster com outros sistemas em sua rede e servidores externos. Sincronizar o horário do seu cluster com servidores NTP externos ajuda a manter a consistência em toda a sua infraestrutura. NetApp configura servidores NTP por padrão para novas implantações do Cloud Volumes ONTAP. No entanto, se eles não estiverem configurados para seus clusters Cloud Volumes ONTAP existentes, você deve configurar servidores NTP para obter uma sincronização precisa do horário dentro e fora da sua rede.

Você pode especificar um servidor NTP usando:

* https://docs.netapp.com/us-en/bluexp-automation/cm/api_ref_resources.html["API do NetApp Console"^].
* O comando ONTAP CLI https://docs.netapp.com/us-en/ontap-cli//cluster-time-service-ntp-server-create.html["criar servidor ntp de serviço de tempo em cluster"^].



NOTE: Se você não configurar um servidor NTP, poderá sofrer interrupções no serviço e sincronização de tempo imprecisa.

.Links relacionados
* Artigo da base de conhecimento (BC): https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs/How_does_a_CVO_cluster_use_NTP["Como um cluster CVO usa o NTP?"]
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["Prepare-se para usar a API"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Fluxos de trabalho do Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/get_identifiers.html#get-the-connector-identifier["Obtenha os identificadores necessários"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/use_rest_apis.html["Use as APIs REST para o NetApp Console"^]

