---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: O AutoSupport monitora proativamente a integridade do seu sistema e envia mensagens ao suporte técnico da NetApp .  Por padrão, o AutoSupport é habilitado em cada nó para enviar mensagens ao suporte técnico usando o protocolo de transporte HTTPS.  É melhor verificar se o AutoSupport pode enviar essas mensagens. 
---
= Verifique a configuração do AutoSupport para o Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O AutoSupport monitora proativamente a integridade do seu sistema e envia mensagens ao suporte técnico da NetApp .  Por padrão, o AutoSupport é habilitado em cada nó para enviar mensagens ao suporte técnico usando o protocolo de transporte HTTPS.  É melhor verificar se o AutoSupport pode enviar essas mensagens.

A única etapa de configuração necessária é garantir que o Cloud Volumes ONTAP tenha conectividade de saída com a Internet.  Para obter detalhes, consulte os requisitos de rede do seu provedor de nuvem.



== Requisitos do AutoSupport

Os nós do Cloud Volumes ONTAP exigem acesso de saída à Internet para o NetApp AutoSupport, que monitora proativamente a integridade do seu sistema e envia mensagens ao suporte técnico da NetApp .

As políticas de roteamento e firewall devem permitir tráfego HTTPS para os seguintes endpoints para que o Cloud Volumes ONTAP possa enviar mensagens de AutoSupport :

* \ https://mysupport.netapp.com/aods/asupmessage
* \ https://mysupport.netapp.com/asupprod/post/1.0/postAsup


Se uma conexão de saída com a Internet não estiver disponível para enviar mensagens do AutoSupport , o NetApp Console configurará automaticamente seus sistemas Cloud Volumes ONTAP para usar o agente do Console como um servidor proxy.  O único requisito é garantir que o grupo de segurança do agente do Console permita conexões _de entrada_ pela porta 3128. Você precisará abrir esta porta depois de implantar o agente do Console.

Se você definiu regras de saída rígidas para o Cloud Volumes ONTAP, também precisará garantir que o grupo de segurança do Cloud Volumes ONTAP permita conexões _de_ saída_ pela porta 3128.


TIP: Se você estiver usando um par HA, o mediador HA não exigirá acesso de saída à Internet.

Depois de verificar se o acesso de saída à Internet está disponível, você pode testar o AutoSupport para garantir que ele pode enviar mensagens.  Para obter instruções, consulte o https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["Documentação do ONTAP : Configurar o AutoSupport"^] .



== Solucionar problemas de configuração do AutoSupport

Se uma conexão de saída não estiver disponível e o Console não conseguir configurar seu sistema Cloud Volumes ONTAP para usar o agente do Console como um servidor proxy, você receberá uma notificação do Console informando que seu sistema não consegue enviar mensagens do AutoSupport . Siga estes passos para resolver este problema.

.Passos
. Conecte-se de forma segura (usando SSH) ao sistema Cloud Volumes ONTAP para usar a CLI do ONTAP .
+
link:task-connecting-to-otc.html["Aprenda como usar SSH para Cloud Volumes ONTAP"] .

. Verifique o status detalhado do subsistema AutoSupport :
+
`autosupport check show-details`

+
A resposta se parece com isto:

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
Se o status da categoria http-https for `OK` Significa que o AutoSupport está configurado corretamente e as mensagens podem ser enviadas.

. Caso contrário, verifique o URL do proxy para cada nó do Cloud Volumes ONTAP :
+
`autosupport show -fields proxy-url`

. Se o parâmetro de URL do proxy estiver vazio, configure o Cloud Volumes ONTAP para usar o agente do Console como um proxy:
+
`autosupport modify -proxy-url \http://<console agent private ip>:3128`

. Verifique novamente o status do AutoSupport :
+
`autosupport check show-details`

. Se o status ainda for falha, verifique se há conectividade entre o Cloud Volumes ONTAP e o agente do Console pela porta. `3128`.
. Se o status ainda indicar falha após a verificação, acesse o agente do Console via SSH.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#connect-to-the-linux-vm["Saiba mais sobre como conectar-se à VM Linux para o agente do console"^]

. Vá para `/opt/application/netapp/cloudmanager/docker_occm/data/`.
. Abra o arquivo de configuração do proxy. `squid.conf`. Esta é a estrutura do arquivo:
+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        http_access allow netapp_support
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on
----
. Se o seu arquivo não tiver uma entrada para o bloco CIDR do sistema Cloud Volumes ONTAP , adicione uma nova entrada e permita o acesso:
+
`acl cvonet src <cidr>`

+
`http_access allow cvonet`

+
Aqui está um exemplo:

+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        acl cvonet src <cidr>
        http_access allow netapp_support
        http_access allow cvonet
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on

----
. Após editar o arquivo de configuração, reinicie o contêiner proxy como `sudo`. Em seguida, dependendo se você estiver usando o Docker ou o Podman, execute estes comandos:
+
Para o Docker, execute `docker restart squid`.

+
Se você estiver usando o Podman, execute `podman restart squid`.

. Volte à CLI do ONTAP e verifique se o Cloud Volumes ONTAP consegue enviar mensagens AutoSupport :
+
`autosupport check show-details`



.Links relacionados
* link:reference-networking-aws.html["Requisitos de rede para Cloud Volumes ONTAP na AWS"^]
* link:reference-networking-azure.html["Requisitos de rede para o Cloud Volumes ONTAP no Azure"^]
* link:reference-networking-gcp.html["Requisitos de rede para o Cloud Volumes ONTAP no Google Cloud"^]

