---
sidebar: sidebar 
permalink: task-getting-started-aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create, console 
summary: Verifique se você concluiu os pré-requisitos para implantar Cloud Volumes ONTAP na AWS. 
---
= Visão geral da implantação do Cloud Volumes ONTAP na AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para implantar Cloud Volumes ONTAP, primeiro você precisa conhecer sua assinatura da AWS e suas licenças do Cloud Volumes ONTAP. Você também deve verificar se possui um agente do NetApp Console criado para sua conta da AWS. Muitas das informações neste tópico precisam ser executadas como parte da configuração do Console antes mesmo de você começar a implantar Cloud Volumes ONTAP.

Você pode integrar o Cloud Volumes ONTAP na AWS usando o AWS Marketplace ou o NetApp Console. A tabela a seguir fornece uma visão geral de alto nível das tarefas que você precisa concluir para implantar o Cloud Volumes ONTAP na AWS. A integração pelo AWS Marketplace é uma experiência simplificada que automatiza a implantação do agente do Console e a associação da assinatura. Para obter informações sobre a integração pelo AWS Marketplace, consulte link:task-onboard-cvo-aws-marketplace.html["Integre o Cloud Volumes ONTAP no AWS Marketplace"].

[cols="20,35,25,25"]
|===
| Tarefa | Descrição | Referência | Notas para implantações em modo privado 


 a| 
Verifique as funções do NetApp Console
 a| 
Antes de criar um agente de Console e executar outras tarefas de implantação para o Cloud Volumes ONTAP, você deve verificar se as funções e permissões do IAM necessárias estão configuradas.
 a| 
Consulte o guia de configuração do NetApp Console: https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html["Funções de acesso do Cloud Volumes ONTAP no NetApp Console"^] https://docs.netapp.com/us-en/console-setup-admin/task-cvo-rbac-setup.html["Configure o acesso baseado em funções para Cloud Volumes ONTAP"^]
 a| 
Verifique se as funções estão configuradas corretamente.



 a| 
Criar um agente do Console
 a| 
Se você ainda não possui um agente de Console, crie um antes de implantar Cloud Volumes ONTAP. Se a implantação for em uma sub-rede sem acesso à internet, instale manualmente o agente de Console e acesse o NetApp Console em execução nesse agente.
 a| 
Consulte o guia de configuração do console: https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-connector-aws.html["Crie um agente de Console na AWS"^]
 a| 
Se a implantação for feita em uma sub-rede sem acesso à internet, instale manualmente o agente do Console e acesse a interface de usuário do NetApp Console que está sendo executada nesse agente do Console. Consulte o guia de configuração do console: https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["Instale manualmente o agente do Console sem acesso à internet"^]



 a| 
Planeje sua configuração
 a| 
O Console oferece pacotes pré-configurados que correspondem aos seus requisitos de carga de trabalho, ou você pode criar sua própria configuração.  Se você escolher sua própria configuração, deverá entender as opções disponíveis.
 a| 
link:task-planning-your-config.html["Planeje sua configuração"]
 a| 
Você precisa ter considerações de planejamento semelhantes para implantações em modo privado.



 a| 
Configure sua rede
 a| 
. Certifique-se de que sua VPC e sub-redes suportem conectividade entre o agente do Console e Cloud Volumes ONTAP.
. Ative o acesso de saída à internet para AutoSupport.
. Configure um endpoint de VPC para Amazon S3 para o armazenamento em camadas de dados. Um endpoint de VPC é necessário se você quiser armazenar em camadas dados frios do Cloud Volumes ONTAP para storage de objetos de baixo custo.

 a| 
link:reference-networking-aws.html["Requisitos de rede para AWS"]
 a| 
O acesso à internet para conexões de saída do AutoSupport não é necessário. Todos os outros requisitos de rede permanecem os mesmos.



 a| 
Configurar o AWS KMS
 a| 
Se você deseja usar a criptografia da Amazon com Cloud Volumes ONTAP, certifique-se de que exista uma Customer Master Key (CMK) ativa e modifique a política de chave para adicionar a função do IAM para o agente do Console como um usuário de chave.
 a| 
link:task-setting-up-kms.html["Configurar o AWS KMS"]
 a| 
Etapas semelhantes se aplicam a implantações em modo privado.



 a| 
Implante Cloud Volumes ONTAP a partir do Console
 a| 
Após cumprir todos os pré-requisitos, você pode concluir as etapas do assistente para implantar Cloud Volumes ONTAP na AWS.
 a| 
* link:task-quick-deploy-aws.html["Implante o Cloud Volumes ONTAP com a criação rápida na AWS"]
* link:task-deploying-otc-aws.html["Implante Cloud Volumes ONTAP usando opções avançadas"]

 a| 
O modo privado suporta apenas a implantação avançada. Antes de iniciar a implantação, certifique-se de que você adquiriu uma licença do Cloud Volumes ONTAP da NetApp. As implantações em modo privado dependem de licenças BYOL. Assinaturas do Marketplace não são compatíveis para cobrança do uso do Cloud Volumes ONTAP. Obtenha o arquivo de licença da NetApp e faça o upload durante a implantação. Consulte:

* link:concept-license-management.html["Gerenciamento de licenças"]
* link:task-manage-node-licenses.html["Gerenciar licenças BYOL"]
* link:task-deploying-otc-aws.html["Implante Cloud Volumes ONTAP usando opções avançadas"]


|===
.Links relacionados
* https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-bluexp.html["Crie um agente de console para AWS"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["Crie um agente de console no AWS Marketplace"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-on-prem.html["Instalar e configurar um agente do Console no local"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-aws.html["Permissões da AWS para o agente do Console"^]

