= O Cloud Volumes ONTAP 9.19.1
:allow-uri-read: 




[[cloud-volumes-ontap-9-19-1]]
=== O Cloud Volumes ONTAP 9.19.1

Agora você pode usar o NetApp Console para implantar e gerenciar a versão de Disponibilidade Geral (GA) do Cloud Volumes ONTAP 9.19.1 na Amazon Web Service (AWS) e no Google Cloud. Esta versão não está disponível para implantação e atualização no Microsoft Azure (Azure).

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["Saiba mais sobre esta versão do Cloud Volumes ONTAP"^].



[[ability-to-convert-node-based-licenses-to-capacity-based-licensing-in-private-mode]]
=== Capacidade de converter licenças baseadas em nós em licenciamento baseado em capacidade no modo privado

NetApp tem o prazer de anunciar o licenciamento baseado em capacidade para implantações do Cloud Volumes ONTAP em modo privado. Agora você pode otimizar os custos das suas implantações do Cloud Volumes ONTAP em modo privado convertendo sua licença baseada em nós para o modelo de licenciamento baseado em capacidade. Para suas implantações em modo privado, você pode adquirir um pacote Essentials (Bring-Your-Own License ou BYOL) diretamente da NetApp com uma capacidade similar à da sua licença baseada em nós existente.

Essa opção de conversão é compatível com o plano gradual da NetApp de migrar do modelo de licenciamento baseado em nós para o modelo de licenciamento baseado em capacidade. Ao contrário do modelo de licenciamento baseado em nós, que aloca uma capacidade fixa para cada sistema, o modelo de licenciamento baseado em capacidade utiliza um pool de capacidade compartilhado entre seus sistemas Cloud Volumes ONTAP, oferecendo a você maior flexibilidade para redistribuir cargas de trabalho conforme suas necessidades de armazenamento mudam.

.Links relacionados
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses["Fim da disponibilidade de licenças baseadas em nós"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-convert-node-capacity.html#conversion-in-a-private-mode-deployment["Conversão em uma implantação de modo privado"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html["Gerencie licenças baseadas em nós para o Cloud Volumes ONTAP"^]

