= Implante o Cloud Volumes ONTAP em modo privado
:allow-uri-read: 




[[deploy-cloud-volumes-ontap-in-private-mode]]
== Implante o Cloud Volumes ONTAP em modo privado

Você pode implantar o Cloud Volumes ONTAP em modo privado seguindo um processo de conversão documentado, passo a passo, diretamente em seu ambiente existente. Na implantação em modo privado, o Cloud Volumes ONTAP é implantado em sua própria nuvem privada (VPC) ou rede virtual (VNet) e não está conectado à internet pública. Você pode usar a implantação em modo privado para atender aos requisitos de segurança e conformidade da sua organização.

As implantações em modo privado anteriormente utilizavam apenas licenças baseadas em nós que você podia adquirir da NetApp. A licença baseada em nós é a licença de geração anterior para o Cloud Volumes ONTAP. NetApp havia restringido a compra, extensão e renovação de licenças baseadas em nós, salvo exceções, desde  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["2025-06-25"]. A partir de 31 de julho de 2026, o licenciamento baseado em nós atingirá o fim da disponibilidade (EOA) para esses casos excepcionais, como United States Public Sector (USPS) e outras implantações em modo privado.

Se você tiver uma implantação privada com uma licença baseada em nó, após isso, você:

* Não é mais possível comprar ou renovar sua licença baseada em nó.
* Não é possível acessar os recursos e aprimoramentos mais recentes.
* Continue a ter maior rigidez operacional devido às restrições baseadas em nós.
* Será necessário migrar para uma licença baseada em capacidade no modo privado assim que a licença baseada em nó expirar. Para obter instruções, consulte  https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-convert-node-capacity.html["Converter licenças baseadas em nós para baseadas em capacidade"^].

